### ISSUE TITLE
pumpaljuset

### ISSUE THREAD

**Issue by local-minimum** [local-minimum/ld47#10]
pumpan har en ljuskälla på sig som alltid ska vara i pumpans huvud

**Comment by sloppydemon** [comment]
Kanske går att lägga ljuskällan som child till pumpans Head-bone?

**Comment by local-minimum** [comment]
förhoppningsvis, tänkte det men under LD men våga inte ifall det skulle bråka med animationerna och va lite för trött på slutet

**Comment by sloppydemon** [comment]
Jag testade ju ändå att lägga på en lookat-restraint på Head ett tag och det blev ju inte bra men animationen funkade ju som den skulle annars. Det är dessutom sista bone i den kedjan så det borde inte kunna störa nåt. Så jag tycker det är värt att testa. Och just det, när jag testade att childa hjälmen till Head-bone i mitt andra spel så ändrade det inget annat vad jag kunde se.

**Comment by local-minimum** [comment]
yes bra. då e det bara att hitta Head och lägga lightet i det

**Comment by sloppydemon** [comment]
Testa att lägga en parent constraint på ljuset och koppla till Head-bone på det sättet (i min test-scen för att inte råka ta sönder nåt), verkar funka.

**Comment by local-minimum** [comment]
nice

**Comment by local-minimum** [comment]
gjorde ett litet script (ifall vi vill ha annan funktionalitet sen på pumpansljus senare) som sätter IKHead till parent för ljuset.
